# Generated by Django 5.1.1 on 2024-10-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProcessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('manufacturer', models.CharField(max_length=30)),
                ('nano_review_score', models.IntegerField()),
                ('nano_review_label', models.CharField(max_length=10)),
                ('antutu_score', models.IntegerField()),
                ('geek_bench_score_single', models.IntegerField(null=True)),
                ('geek_bench_score_multi', models.IntegerField(null=True)),
                ('geek_bench_score_gpu', models.IntegerField(null=True)),
                ('score_3d_mark', models.IntegerField(null=True)),
                ('fps_3d_mark', models.IntegerField(null=True)),
                ('cpu_frequency', models.IntegerField(null=True)),
                ('architecture', models.CharField(max_length=200, null=True)),
                ('cores', models.IntegerField(null=True)),
                ('l2_cache', models.IntegerField(null=True)),
                ('l3_cache', models.IntegerField(null=True)),
                ('process_nanometers', models.IntegerField(null=True)),
                ('tdp_watt', models.IntegerField(null=True)),
                ('gpu_name', models.CharField(max_length=200, null=True)),
                ('gpu_frequency', models.IntegerField(null=True)),
                ('gpu_flops_gigaflops', models.IntegerField(null=True)),
                ('gpu_pipelines', models.IntegerField(null=True)),
                ('memory_type', models.CharField(max_length=20, null=True)),
                ('memory_frequency', models.IntegerField(null=True)),
                ('memory_max_size', models.IntegerField(null=True)),
                ('max_display_resolution', models.CharField(max_length=60, null=True)),
                ('max_camera_resolution', models.CharField(blank=True, max_length=60)),
                ('video_capture', models.CharField(max_length=60, null=True)),
                ('video_playbacks', models.CharField(max_length=60, null=True)),
                ('support_4g', models.CharField(blank=True, max_length=30)),
                ('support_5g', models.BooleanField(null=True)),
                ('download_max_speed', models.IntegerField(null=True)),
                ('upload_max_speed', models.IntegerField(null=True)),
                ('wifi_version', models.IntegerField()),
                ('bluetooth_version', models.DecimalField(decimal_places=1, max_digits=4)),
                ('announced', models.DateField(null=True)),
            ],
        ),
    ]
