# Generated by Django 5.1.1 on 2024-10-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_processors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileprocessor',
            name='category',
            field=models.CharField(choices=[('Mid', 'Mid'), ('range', 'Range')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobileprocessor',
            name='bluetooth_version',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='mobileprocessor',
            name='support_4g',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mobileprocessor',
            name='wifi_version',
            field=models.IntegerField(null=True),
        ),
    ]
