# Generated by Django 5.1.1 on 2024-10-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_processors', '0002_mobileprocessor_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileprocessor',
            name='clock',
            field=models.IntegerField(null=True),
        ),
    ]
