# Generated by Django 5.1.1 on 2024-10-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_processors', '0003_mobileprocessor_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileprocessor',
            name='cores_summary',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
