# Generated by Django 5.1.1 on 2024-11-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_processors', '0004_mobileprocessor_cores_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileprocessor',
            name='l2_cache',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mobileprocessor',
            name='l3_cache',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
