# Generated by Django 5.1.1 on 2024-11-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_processors', '0007_alter_mobileprocessor_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileprocessor',
            name='category',
            field=models.CharField(choices=[('Flagship', 'Flagship'), ('Mid range', 'Intermediário'), ('Low end', 'Entrada')], max_length=20, null=True),
        ),
    ]
