# Generated by Django 5.1.1 on 2025-01-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_processors', '0008_alter_mobileprocessor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileprocessor',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
